version: "3.3"

services:
  web:
    restart: always
    build: .
    command: /bin/sh -c /code/entrypoint.prod.sh
    volumes:
      - static_volume:/code/static
    volumes:
      - .:/code
    expose:
      - 8000
    env_file:
      - .env.prod
    networks:
      - reverse-proxy_proxynet
  
  nginx:
    restart: always
    image: nginx:latest
    hostname: bug-tracker-django.kristianms.com
    volumes:
      - static_volume:/code/static
      - type: bind
        source: ./nginx_config/nginx.conf
        target: /etc/nginx/conf.d/default.conf
    expose:
      - 1347
    depends_on:
      - web
    environment:
      - VIRTUAL_HOST=kristianms.com
      - VIRTUAL_PORT=1347
      - LETSENCRYPT_HOST=kristianms.com
      - LETSENCRYPT_EMAIL=kmollerschmidt@gmail.com
      - url=https://kristianms.com
    networks:
      - reverse-proxy_proxynet
 
volumes:
  static_volume: {}

networks:
  reverseproxy_proxynet:
    external: true