# Generated by Django 3.1.13 on 2021-07-21 12:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mails',
            new_name='Mail',
        ),
    ]
